### ISSUE TITLE
1.0.0.0 Checklist

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#335]
- [ ] Rewrite Redirection Core Code
    - [ ] Add support for non-default browser
        - [ ] Add support for relative directory portable browsers
- [ ] Add ability to download updates if the user so chooses
- [ ] Add additional alternatives for Services
    - [ ] Home -> News Home (news.google.com)
    - [ ] News -> Create bounty item in discussions
    - [ ] Stocks -> Create bounty item in discussions
    - [ ] Traffic -> Create bounty item in discussions
- [ ] Add UI Translation Support
    - [ ] Add _Translation calls
    - [ ] Create [crowdin](https://crowdin.com/) account
- [ ] Swap to Metro UI
    - [ ] Add Rounded Corners
    - [ ] Add Presets (Google, DuckDuckGo, None)
    - [ ] Add Option to disable update check
- [ ] Rewrite Installer Code
    - [ ] Handle Portable Installs
        - [ ] Don't write to Registry
